### ISSUE TITLE
NullPointerException on every start  - Encryption disabled

### ISSUE THREAD

**Issue by darenegade** [VictorAlbertos/RxCache#45]
First: Thx for this awesome library. 😄 

I'm using a simple RXCache implementation with no encryption on Android with Retrofit2. Everything works fine. But on every start I get a NullPointerException, because the `BuiltInEncryptor` tries to generate a secret Key in `generateSecretKey(String key)`. Due to no encryption the string key is `null`. Here is the head of the stackTrace:
```
06-29 14:04:11.647 7209-7235/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.encrypt.BuiltInEncryptor.generateSecretKey(BuiltInEncryptor.java:81)
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.encrypt.BuiltInEncryptor.initCiphers(BuiltInEncryptor.java:67)
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.encrypt.BuiltInEncryptor.decrypt(BuiltInEncryptor.java:55)
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.encrypt.FileEncryptor.decrypt(FileEncryptor.java:53)
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.Disk.retrieveRecord(Disk.java:187)
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.cache.EvictExpiredRecordsPersistence.startEvictingExpiredRecords(EvictExpiredRecordsPersistence.java:48)
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.ProxyProviders$1.call(ProxyProviders.java:59)
06-29 14:04:11.647 7209-7235/? W/System.err:     at io.rx_cache.internal.ProxyProviders$1.call(ProxyProviders.java:57)
```

The root cause seems to be in `EvictExpiredRecordsPersistence`. The Method `persistence.retrieveRecord(key, false, getEncryptKey.getKey());` returns null for a key and thats why he tries to get the record with encryption enabled.

Is this a Problem in RXCache or am I missing a configuration?

Thx for the help.

My Config:
```java
public interface UserCache {

  Observable<Reply<UserDto>> usersFindOne(
      Observable<UserDto> oUser, DynamicKey userId, EvictDynamicKey update);

  Observable<Reply<List<UserDto>>> usersFindAll(
      Observable<List<UserDto>> oUsers, EvictProvider update);

.... more methods
}
```
```java
public interface RouteCache {

  Observable<Reply<RouteDto>> routesFindOne(
      Observable<RouteDto> oRoute, DynamicKey id, EvictDynamicKey update);

  Observable<Reply<List<RouteDto>>> routesFindAll(
      Observable<List<RouteDto>> oRoutes, EvictProvider evictProvider);

...more methods
```
```java
public class CacheFactory {
  
  private static <S> S createCache(Class<S> serviceClass, File cacheDir){
    return new RxCache.Builder()
        .useExpiredDataIfLoaderNotAvailable(true)
        .persistence(cacheDir, new JacksonSpeaker())
        .using(serviceClass);
  }

  public static UserCache getUserCache(File cacheDir){
    return createCache(UserCache.class, cacheDir);
  }

  public static RouteCache getRouteCache(File cacheDir){
    return createCache(RouteCache.class, cacheDir);
  }
}
```

**Comment by VictorAlbertos** [comment]
Try the new release 1.5.5 please ;)

**Comment by darenegade** [comment]
Exception is gone. Thanks a lot 👍

**Comment by VictorAlbertos** [comment]
You are welcome ;)
