### ISSUE TITLE
Breaks with data binding

### ISSUE THREAD

**Issue by sahityaPasnoor** [VictorAlbertos/RxCache#56]
When used along with Databinding and dagger, App doesn't  compile and breaks the Data binding stuff.

**Comment by VictorAlbertos** [comment]
I don't use Databinding. So I have not experience this issue. If you want me to help I'm going to need the stack trace for the failing build.

**Comment by sahityaPasnoor** [comment]
When I add the Reactive Cache gradle dependency, the app simply says "cannot Find symbol BR" at build time no other stack trace. I guess this is because of APT plugin conflict.

**Comment by VictorAlbertos** [comment]
Have you tried these proposals?

http://stackoverflow.com/questions/30776466/cannot-find-symbol-br-in-android-data-binding

**Comment by sahityaPasnoor** [comment]
I have tried everything possible, but none of them works because it has conflict it has with apt in my project and other apt version in your library.

**Comment by VictorAlbertos** [comment]
Jut to let you know, RxCache doesn't use the android apt plugin. It uses the apt plugin created by tbroyer for pure java projects. 

https://github.com/tbroyer/gradle-apt-plugin

So, I'm not completely sure that that could be the problem. Nevertheless, have you tried to force to use specific versions with resolutionStrategy?

```gradle
configurations.all {
    resolutionStrategy {
        force "com.google.android.gms:play-services-gam:9.4.0"
    }
}
```

**Comment by sahityaPasnoor** [comment]
Okay, i'll try this and let you know.

**Comment by sahityaPasnoor** [comment]
Got the root of the isssue .   I explored  "**tbroyer**"  github and found that he mention the gradle compatibility with dagger 2. I had to add **apt     "com.google.dagger:dagger-compiler:2.6"** to my gradle script inorder to compile dagger annotations. Finally got it running. Thanks for providing github link in the last comment. 
Anybody looking for stacktrace, here it is.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':Panel_Android:compileDevelopmentDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: dagger/internal/ScopedProvider
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: dagger/internal/ScopedProvider
	at dagger.internal.codegen.ComponentGenerator.initializeFactoryForProvisionBinding(ComponentGenerator.java:1237)
	at dagger.internal.codegen.ComponentGenerator.initializeFrameworkTypes(ComponentGenerator.java:997)
	at dagger.internal.codegen.ComponentGenerator.writeComponent(ComponentGenerator.java:444)
	at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:235)
	at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:125)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:53)
	at dagger.internal.codegen.ComponentProcessingStep.processComponents(ComponentProcessingStep.java:152)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:89)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:228)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 34 more
Caused by: java.lang.ClassNotFoundException: dagger.internal.ScopedProvider
	... 51 more

**Comment by VictorAlbertos** [comment]
I'm glad that the issue is solved ;) And thanks for sharing your solution, it may help other people.
