### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by jasonni** [VictorAlbertos/RxCache#81]
Hi @VictorAlbertos 
I meet this exception and don't know why it happens...
I use **TypeAdapter** to build gson
Do you have any idea?
 
```
	java.lang.IllegalStateException
                           at com.google.gson.stream.JsonWriter.name(JsonWriter.java:390)
                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:242)
                           at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107)
                           at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
                           at com.google.gson.Gson.toJson(Gson.java:669)
                           at com.google.gson.Gson.toJson(Gson.java:648)
                           at com.google.gson.Gson.toJson(Gson.java:603)
                           at io.victoralbertos.jolyglot.GsonSpeaker.toJson(GsonSpeaker.java:53)
                           at io.rx_cache2.internal.Disk.save(Disk.java:111)
                           at io.rx_cache2.internal.Disk.saveRecord(Disk.java:57)
                           at io.rx_cache2.internal.cache.SaveRecord.save(SaveRecord.java:51)
                           at io.rx_cache2.internal.cache.TwoLayersCache.save(TwoLayersCache.java:45)
```

**Comment by VictorAlbertos** [comment]
Please, review your configuration before submitting here this kind of issues. I can do nothing with your information. If you think that there is a bug, show it with a PR containing a test.
