### ISSUE TITLE
 Caused by: java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by ykrank** [VictorAlbertos/RxCache#85]
when in debug buildtype, everything is ok.
but if use proguard-android-optimize in release type, app crash when RxCache init.
error like this；
` Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                       at io.rx_cache2.internal.ProxyTranslator.getObjectFromMethodParam(Proguard:138)
                                                       at io.rx_cache2.internal.ProxyProviders$1.io.rx_cache2.internal.ProxyTranslator.getDynamicKey(Proguard:18061)
                                                                                                 io.rx_cache2.internal.ProxyTranslator.processMethod
                                                                                                 call
                                                                                                 call
                                                       at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(Proguard:32)
                                                       at io.reactivex.Observable.subscribe(Proguard:10841)
                                                       at io.reactivex.Observable.blockingFirst(Proguard:4725)
                                                       at io.rx_cache2.internal.ProxyProviders.invoke(Proguard:95)
                                                       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                       at $Proxy5.c(Unknown Source)
                                                       at me.ykrank.s1next.view.fragment.ForumFragment.getSourceObservable$164c503d(Proguard:89)
                                                       at me.ykrank.s1next.view.fragment.BaseRecyclerViewFragment.load(Proguard:295)
                                                       at me.ykrank.s1next.view.fragment.BaseRecyclerViewFragment.onActivityCreated(Proguard:151)
                                                       at android.support.v4.app.FragmentManagerImpl.android.support.v4.app.Fragment.performActivityCreated(Proguard:11201)
                                                                                                     moveToState
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Proguard:1528)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(Proguard:1595)
                                                       at android.support.v4.app.BackStackRecord.executeOps(Proguard:758)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(Proguard:2363)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Proguard:2149)
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(Proguard:2103)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(Proguard:2013)
                                                       at android.support.v4.app.FragmentController.execPendingActions(Proguard:388)
                                                       at android.support.v4.app.FragmentActivity.onStart(Proguard:607)
                                                       at android.support.v7.app.AppCompatActivity.onStart(Proguard:178)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
                                                       at android.app.Activity.performStart(Activity.java:6930)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)?
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)?
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)?
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)?
                                                       at android.os.Looper.loop(Looper.java:156)?
                                                       at android.app.ActivityThread.main(ActivityThread.java:6524)?
                                                       at java.lang.reflect.Method.invoke(Native Method)?
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)?
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)?
`

**Comment by ykrank** [comment]
this happen even add proguard:
-dontwarn io.rx_cache.internal.**
-keepclassmembers enum io.rx_cache.Source { *; }

**Comment by ykrank** [comment]
after decompile apk, i find that happen because proguard remove annotation parameter after optimize.
just add
`-keepclassmembernames class * {
    @io.rx_cache2.* <methods>;
}`
if use optimize proguard
